### ISSUE TITLE
Criar cadastro de animal

### ISSUE THREAD

**Issue by danconte72** [uniarp/projeto_3#1]
## Diagrama 
![image](https://github.com/user-attachments/assets/18774ddd-37d6-48db-a649-1d70945a9c7c)

## Atributos
- nome, cpf, rg
## Prototipo

![image](https://github.com/user-attachments/assets/0a276a5c-0b2d-484b-88bc-9a069f00b404)

**Comment by EdisonMargoti** [comment]
dale

**Comment by danconte72** [comment]
@danconte72 nao precisa passaporte do animal?

**Comment by danconte72** [comment]
> @danconte72 nao precisa passaporte do animal?

nao precisa

**Comment by EdisonMargoti** [comment]
@danconte72 claro, como ele vai sair do pais ?
